from __future__ import annotations

import hashlib
import io
import tarfile
import zipfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import pytest

from moseq2_test.data import CacheLayout, extract_object, fetch_object, verify_object
from moseq2_test.errors import InvalidConfiguration, MissingInput
from moseq2_test.models import FixtureObject


def fixture(path: Path, *, unpack: str = "none", members: int | None = None) -> FixtureObject:
    payload = path.read_bytes()
    return FixtureObject(
        id="synthetic-fixture",
        kind="archive" if unpack != "none" else "fixture",
        filename=path.name,
        size=len(payload),
        sha256=hashlib.sha256(payload).hexdigest(),
        canonical_urls=["https://example.invalid/object"],
        publication_status="approved-by-project-owner",
        trust="trusted-baseline",
        unpack=unpack,
        profiles=["synthetic"],
        license_id="test-only",
        citation="synthetic test fixture",
        source="generated by test",
        max_unpacked_bytes=1024,
        max_members=members,
    )


def test_offline_mirror_populates_content_addressed_cache(tmp_path: Path) -> None:
    source = tmp_path / "mirror" / "value.bin"
    source.parent.mkdir()
    source.write_bytes(b"verified bytes")
    item = fixture(source)
    layout = CacheLayout(tmp_path / "cache")

    result = fetch_object(layout, item, mirror=source.parent, offline=True)

    assert result == layout.object_path(item.sha256)
    assert result.read_bytes() == b"verified bytes"
    assert result.stat().st_mode & 0o222 == 0


def test_corrupt_cache_is_rejected_offline(tmp_path: Path) -> None:
    source = tmp_path / "value.bin"
    source.write_bytes(b"expected")
    item = fixture(source)
    layout = CacheLayout(tmp_path / "cache")
    layout.prepare()
    destination = layout.object_path(item.sha256)
    destination.parent.mkdir(parents=True)
    destination.write_bytes(b"corrupt")

    with pytest.raises(MissingInput):
        fetch_object(layout, item, offline=True)


def test_concurrent_fetches_converge_on_one_object(tmp_path: Path) -> None:
    mirror = tmp_path / "mirror"
    mirror.mkdir()
    source = mirror / "value.bin"
    source.write_bytes(b"same bytes" * 1000)
    item = fixture(source)
    layout = CacheLayout(tmp_path / "cache")

    with ThreadPoolExecutor(max_workers=4) as pool:
        paths = list(
            pool.map(
                lambda _: fetch_object(layout, item, mirror=mirror, offline=True),
                range(4),
            )
        )

    assert len(set(paths)) == 1
    verify_object(paths[0], item)
    assert not list(layout.temporary.glob("*.partial"))


@pytest.mark.parametrize("name", ["../escape", "/absolute", "safe/../../escape"])
def test_zip_path_traversal_is_rejected(tmp_path: Path, name: str) -> None:
    archive = tmp_path / "bad.zip"
    with zipfile.ZipFile(archive, "w") as handle:
        handle.writestr(name, b"bad")
    item = fixture(archive, unpack="zip", members=1)
    layout = CacheLayout(tmp_path / "cache")
    layout.prepare()
    destination = layout.object_path(item.sha256)
    destination.parent.mkdir(parents=True)
    destination.write_bytes(archive.read_bytes())

    with pytest.raises(InvalidConfiguration):
        extract_object(layout, item)


def test_tar_links_and_special_files_are_rejected(tmp_path: Path) -> None:
    archive = tmp_path / "bad.tar.gz"
    with tarfile.open(archive, "w:gz") as handle:
        info = tarfile.TarInfo("link")
        info.type = tarfile.SYMTYPE
        info.linkname = "target"
        handle.addfile(info)
    item = fixture(archive, unpack="tar.gz", members=1)
    layout = CacheLayout(tmp_path / "cache")
    layout.prepare()
    destination = layout.object_path(item.sha256)
    destination.parent.mkdir(parents=True)
    destination.write_bytes(archive.read_bytes())

    with pytest.raises(InvalidConfiguration):
        extract_object(layout, item)


def test_safe_zip_is_extracted_read_only(tmp_path: Path) -> None:
    archive = tmp_path / "good.zip"
    with zipfile.ZipFile(archive, "w") as handle:
        handle.writestr("/", b"")
        handle.writestr("nested/value.txt", b"hello")
    item = fixture(archive, unpack="zip", members=2)
    layout = CacheLayout(tmp_path / "cache")
    layout.prepare()
    destination = layout.object_path(item.sha256)
    destination.parent.mkdir(parents=True)
    destination.write_bytes(archive.read_bytes())

    extracted = extract_object(layout, item)

    value = extracted / "nested" / "value.txt"
    assert value.read_bytes() == b"hello"
    assert value.stat().st_mode & 0o222 == 0


def test_archive_decompression_ceiling_is_enforced(tmp_path: Path) -> None:
    archive = tmp_path / "large.zip"
    with zipfile.ZipFile(archive, "w") as handle:
        handle.writestr("value", b"x" * 2048)
    item = fixture(archive, unpack="zip", members=1).model_copy(update={"max_unpacked_bytes": 1024})
    layout = CacheLayout(tmp_path / "cache")
    layout.prepare()
    destination = layout.object_path(item.sha256)
    destination.parent.mkdir(parents=True)
    destination.write_bytes(archive.read_bytes())

    with pytest.raises(InvalidConfiguration):
        extract_object(layout, item)


def test_tar_regular_file_round_trip(tmp_path: Path) -> None:
    archive = tmp_path / "good.tar.gz"
    with tarfile.open(archive, "w:gz") as handle:
        payload = b"hello"
        info = tarfile.TarInfo("nested/value.txt")
        info.size = len(payload)
        handle.addfile(info, io.BytesIO(payload))
    item = fixture(archive, unpack="tar.gz", members=1)
    layout = CacheLayout(tmp_path / "cache")
    layout.prepare()
    destination = layout.object_path(item.sha256)
    destination.parent.mkdir(parents=True)
    destination.write_bytes(archive.read_bytes())

    extracted = extract_object(layout, item)
    assert (extracted / "nested" / "value.txt").read_bytes() == b"hello"
