from __future__ import annotations

import hashlib
import io
import json
import os
import subprocess
import sys
import tarfile
import xml.etree.ElementTree as ET
import zipfile
from datetime import UTC, datetime
from pathlib import Path

import pytest

from moseq2_test.data import CacheLayout, fetch_object
from moseq2_test.failure_policy import junit_observations
from moseq2_test.models import FixtureManifest, FixtureObject, SourceRecord
from moseq2_test.registry import profile
from moseq2_test.sandbox import Sandbox
from moseq2_test.suites.historical_regression import (
    _extract_locked_source_archive,
    _offline_url_environment,
    _parse_junit,
    _prepare_test_tree,
    _stage_fixture,
    _test_command,
)


def test_profile_has_one_informative_step_per_locked_package() -> None:
    selected = profile("historical-regression")
    assert selected.implemented is True
    assert len(selected.steps) == 8
    assert [step.id for step in selected.steps] == [
        f"historical-tests-{package}" for package in selected.packages
    ]
    extract_step = selected.steps[0]
    assert extract_step.fixtures == [
        "historical-fixtures--moseq2-extract-zip",
        "classifiers--flip-classifier-k2-largemicewithfiber-pkl",
        "classifiers--flip-classifier-k2-c57-10to13weeks-pkl",
    ]


def test_junit_summary_preserves_failures_and_collection_errors(tmp_path: Path) -> None:
    suite = ET.Element("testsuite", tests="3", failures="1", errors="1", skipped="0", time="0.25")
    path = tmp_path / "junit.xml"
    path.write_bytes(ET.tostring(suite, encoding="utf-8", xml_declaration=True))
    assert _parse_junit(path) == {
        "tests": 3,
        "failures": 1,
        "errors": 1,
        "skipped": 0,
        "time": 0.25,
        "parsed": True,
    }


def test_extract_fixture_stages_the_locked_flip_classifier(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    archive = tmp_path / "moseq2-extract.zip"
    with zipfile.ZipFile(archive, "w") as handle:
        handle.writestr("fixture.txt", b"fixture")
    classifier = tmp_path / "flip_classifier_k2_c57_10to13weeks.pkl"
    classifier.write_bytes(b"classifier")

    def item(path: Path, *, object_id: str, unpack: str) -> FixtureObject:
        payload = path.read_bytes()
        return FixtureObject(
            id=object_id,
            kind="archive" if unpack != "none" else "trusted-pickle",
            filename=path.name,
            size=len(payload),
            sha256=hashlib.sha256(payload).hexdigest(),
            canonical_urls=["https://example.invalid/object"],
            publication_status="approved-by-project-owner",
            trust="trusted-baseline",
            unpack=unpack,
            profiles=["historical-regression"],
            license_id="test-only",
            citation="synthetic fixture",
            source="generated by test",
            max_unpacked_bytes=1024 if unpack != "none" else None,
            max_members=1 if unpack != "none" else None,
        )

    archive_item = item(
        archive,
        object_id="historical-fixtures--moseq2-extract-zip",
        unpack="zip",
    )
    classifier_item = item(
        classifier,
        object_id="classifiers--flip-classifier-k2-c57-10to13weeks-pkl",
        unpack="none",
    )
    manifest = FixtureManifest(
        fixture_set="historical-v1",
        status="immutable",
        created_at=datetime.now(UTC),
        maintainer="test",
        terms="https://example.invalid/terms",
        objects=[archive_item, classifier_item],
    )
    monkeypatch.setattr(
        "moseq2_test.suites.historical_regression.fixture_manifest",
        lambda _name: manifest,
    )
    cache = tmp_path / "cache"
    layout = CacheLayout(cache)
    fetch_object(layout, archive_item, mirror=tmp_path, offline=True)
    fetch_object(layout, classifier_item, mirror=tmp_path, offline=True)

    destination = tmp_path / "test-source"
    destination.mkdir()
    _stage_fixture("moseq2-extract", destination, cache)

    assert (destination / "data" / "fixture.txt").read_bytes() == b"fixture"
    staged_classifier = destination / "data" / "flip" / classifier.name
    assert staged_classifier.read_bytes() == b"classifier"
    assert staged_classifier.stat().st_mode & 0o200


def test_historical_download_urls_resolve_only_to_hash_locked_local_fixtures(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    c57 = tmp_path / "flip_classifier_k2_c57_10to13weeks.pkl"
    large = tmp_path / "flip_classifier_k2_largemicewithfiber.pkl"
    c57.write_bytes(b"c57-classifier")
    large.write_bytes(b"large-mice-classifier")

    def item(path: Path, object_id: str) -> FixtureObject:
        return FixtureObject(
            id=object_id,
            kind="trusted-pickle",
            filename=path.name,
            size=path.stat().st_size,
            sha256=hashlib.sha256(path.read_bytes()).hexdigest(),
            canonical_urls=["https://example.invalid/" + path.name],
            publication_status="approved-by-project-owner",
            trust="trusted-baseline",
            unpack="none",
            profiles=["historical-regression"],
            license_id="test-only",
            citation="synthetic fixture",
            source="generated by test",
        )

    objects = [
        item(large, "classifiers--flip-classifier-k2-largemicewithfiber-pkl"),
        item(c57, "classifiers--flip-classifier-k2-c57-10to13weeks-pkl"),
    ]
    manifest = FixtureManifest(
        fixture_set="historical-v1",
        status="immutable",
        created_at=datetime.now(UTC),
        maintainer="test",
        terms="https://example.invalid/terms",
        objects=objects,
    )
    monkeypatch.setattr(
        "moseq2_test.suites.historical_regression.fixture_manifest",
        lambda _name: manifest,
    )
    cache = tmp_path / "cache"
    layout = CacheLayout(cache)
    for object_item, source in zip(objects, (large, c57), strict=True):
        fetch_object(layout, object_item, mirror=source.parent, offline=True)
    sandbox = Sandbox.create(tmp_path / "workspace")
    environment, evidence = _offline_url_environment("moseq2-extract", sandbox, cache)
    assert evidence is not None
    assert {item["fixture_id"] for item in evidence["mappings"]} == {
        item.id for item in objects
    }

    script = tmp_path / "exercise_urlretrieve.py"
    output = tmp_path / "downloaded.pkl"
    script.write_text(
        "import urllib.request\n"
        "urllib.request.urlretrieve("
        "'https://storage.googleapis.com/flip-classifiers/"
        "flip_classifier_k2_largemicewithfiber.pkl', "
        + repr(str(output))
        + ")\n",
        encoding="utf-8",
    )
    completed = subprocess.run(
        [sys.executable, str(script)],
        env={**os.environ, **environment},
        capture_output=True,
        text=True,
        check=False,
    )
    assert completed.returncode == 0, completed.stderr
    assert output.read_bytes() == large.read_bytes()

    url_map = json.loads(environment["MOSEQ2_TEST_OFFLINE_URL_MAP"])
    assert set(url_map) == {
        "https://storage.googleapis.com/flip-classifiers/"
        "flip_classifier_k2_largemicewithfiber.pkl",
        "https://storage.googleapis.com/flip-classifiers/"
        "flip_classifier_k2_c57_10to13weeks.pkl",
    }
    script.write_text(
        "import urllib.request\n"
        "urllib.request.urlretrieve('https://example.invalid/unmapped', "
        + repr(str(output))
        + ")\n",
        encoding="utf-8",
    )
    rejected = subprocess.run(
        [sys.executable, str(script)],
        env={**os.environ, **environment},
        capture_output=True,
        text=True,
        check=False,
    )
    assert rejected.returncode != 0
    assert "URL is not a staged moseq2-test fixture" in rejected.stderr


def test_collection_exception_is_normalized_from_pytest_junit(tmp_path: Path) -> None:
    suite = ET.Element("testsuite", tests="1", failures="0", errors="1")
    case = ET.SubElement(suite, "testcase", classname="", name="collection failure")
    error = ET.SubElement(case, "error", message="collection failure")
    error.text = "E   ImportError: cannot import name 'old_api'"
    path = tmp_path / "junit.xml"
    path.write_bytes(ET.tostring(suite, encoding="utf-8", xml_declaration=True))
    observations = junit_observations(
        path,
        scope="historical-regression",
        package="moseq2-app",
        collection_nodeid="tests/gui_tests/test_main.py",
    )
    assert observations[0].outcome == "error"
    assert observations[0].exception == "ImportError"
    assert observations[0].nodeid == "tests/gui_tests/test_main.py"


def test_test_snapshot_cannot_import_the_source_package(tmp_path: Path) -> None:
    source = tmp_path / "snapshot"
    (source / "pybasicbayes").mkdir(parents=True)
    (source / "pybasicbayes" / "__init__.py").write_text("raise AssertionError\n")
    (source / "tests").mkdir()
    (source / "tests" / "test_public.py").write_text("def test_public(): pass\n")
    sandbox = Sandbox.create(tmp_path / "workspace")
    record = SourceRecord(
        name="pybasicbayes",
        repository="https://github.com/mattjj/pybasicbayes.git",
        commit="a" * 40,
        tree="b" * 40,
        default_branch="master",
        owner="mattjj",
        license_id="MIT",
    )
    destination, evidence = _prepare_test_tree(
        "pybasicbayes",
        record,
        source_override=source,
        source_mirror=None,
        source_archive=None,
        sandbox=sandbox,
        cache_dir=tmp_path / "cache",
        offline=True,
        allow_dirty=False,
    )
    assert not (destination / "pybasicbayes").exists()
    assert (destination / "tests" / "test_public.py").is_file()
    assert evidence["import_root_removed"] is True


def test_locked_source_archive_is_hash_verified_and_safely_staged(tmp_path: Path) -> None:
    archive_path = tmp_path / "pybasicbayes.tar.gz"
    payload = b"def test_public(): pass\n"
    with tarfile.open(archive_path, "w:gz") as archive:
        directory = tarfile.TarInfo("pybasicbayes")
        directory.type = tarfile.DIRTYPE
        archive.addfile(directory)
        tests = tarfile.TarInfo("pybasicbayes/tests")
        tests.type = tarfile.DIRTYPE
        archive.addfile(tests)
        member = tarfile.TarInfo("pybasicbayes/tests/test_public.py")
        member.size = len(payload)
        archive.addfile(member, io.BytesIO(payload))
    record = SourceRecord(
        name="pybasicbayes",
        repository="https://github.com/mattjj/pybasicbayes.git",
        commit="a" * 40,
        tree="b" * 40,
        default_branch="master",
        owner="mattjj",
        license_id="MIT",
    )
    digest = hashlib.sha256(archive_path.read_bytes()).hexdigest()
    destination = tmp_path / "sources" / "pybasicbayes"
    destination.parent.mkdir()

    evidence = _extract_locked_source_archive(record, archive_path, digest, destination)

    assert (destination / "tests" / "test_public.py").read_bytes() == payload
    assert evidence["commit"] == record.commit
    assert evidence["source_archive_sha256"] == digest


def test_profile_command_becomes_an_explicit_target_command(tmp_path: Path) -> None:
    step = profile("historical-regression").steps[0]
    command = _test_command(step, tmp_path / "bin" / "python", tmp_path / "junit.xml")
    assert command[:3] == [str(tmp_path / "bin" / "python"), "-m", "pytest"]
    assert command[-1] == f"--junitxml={tmp_path / 'junit.xml'}"
